apiVersion: v1
kind: Service
metadata:
  name: petcam-service
  labels:
    app: petcam
spec:
  type: NodePort
  selector:
    app: petcam
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443
      nodePort: 31200
